// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reco.Api.Data;

#nullable disable

namespace Reco.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506182629_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Reco.Api.Data.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.DiaryEntryEntity", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("Date");

                    b.ToTable("diary_entries", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.SessionEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT")
                        .HasColumnName("album");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<int?>("ConversationBlock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversation_block");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("is_active");

                    b.Property<string>("Mood")
                        .HasColumnType("TEXT")
                        .HasColumnName("mood");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("me")
                        .HasColumnName("user_label");

                    b.HasKey("Id");

                    b.HasIndex("ConversationBlock")
                        .HasDatabaseName("idx_se_conversation_block");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_se_is_active");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.SessionStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("session_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
