// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reco.Api.Data;

#nullable disable

namespace Reco.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603000003_Phase22_ExtractResponseFormatAppendix")]
    partial class Phase22_ExtractResponseFormatAppendix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Reco.Api.Data.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.DiaryEntryEntity", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("Date");

                    b.ToTable("diary_entries", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.PromptSetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RecommendationPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recommendation_prompt");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UseSession")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("use_session");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_ps_name");

                    b.ToTable("prompt_sets", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.RecommendationHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT")
                        .HasColumnName("album");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artist");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("idx_rh_recorded_at");

                    b.ToTable("recommendation_history", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.SessionEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT")
                        .HasColumnName("album");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<int?>("ConversationBlock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversation_block");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("is_active");

                    b.Property<string>("Mood")
                        .HasColumnType("TEXT")
                        .HasColumnName("mood");

                    b.Property<string>("PromptSetName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Default")
                        .HasColumnName("prompt_set_name");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("me")
                        .HasColumnName("user_label");

                    b.HasKey("Id");

                    b.HasIndex("ConversationBlock")
                        .HasDatabaseName("idx_se_conversation_block");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_se_is_active");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("Reco.Api.Data.Entities.SessionStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("session_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
